name: DevWorkspace Operator CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-on-minikube:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Minikube-Kubernetes
        uses: manusa/actions-setup-minikube@v2.14.0
        with:
          minikube version: 'v1.35.0'
          kubernetes version: 'v1.33.0'
          github token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install and Enable Minikube addons metrics-server
        run: |
          minikube addons enable metrics-server
          kubectl rollout status deployment/metrics-server -n kube-system --timeout=60s

      - name: Install and Wait for cert-manager to be ready
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.18.2/cert-manager.yaml
          kubectl rollout status deployment/cert-manager -n cert-manager --timeout=120s

      - name: Enable and Wait for Ingress addon
        run: |
          minikube addons enable ingress
          kubectl rollout status deployment/ingress-nginx-controller -n ingress-nginx --timeout=120s

      - name: Clone DevWorkspace Operator repo
        run: |
          git clone https://github.com/devfile/devworkspace-operator.git devworkspace-operator
          cd devworkspace-operator
          git checkout main 

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build DevWorkspace Operator
        run: |
          cd devworkspace-operator
          export DWO_IMG=ttl.sh/devworkspace-operator:15m
          export NAMESPACE=devworkspace-controller
          make docker

      - name: Deploy DevWorkspace Operator to Minikube
        run: |
          cd devworkspace-operator
          make install
          kubectl rollout status deployment/devworkspace-controller-manager -n devworkspace-controller --timeout=120s

      - name: List DevWorkspace Operator pods
        run: |
          kubectl get pods -n devworkspace-controller
          kubectl top pods -n devworkspace-controller
